### ISSUE TITLE
Разделитель команд

### ISSUE THREAD

**Issue by vildar82** [ZFi88/FootballMixerBot#1]
Просьба добавить разделитель команд - пустую строку:
Сейчас так:
![image](https://user-images.githubusercontent.com/1446481/37912328-fb8b6b14-311a-11e8-95e4-ac65e7f2e709.png)
Нужно так:
![image](https://user-images.githubusercontent.com/1446481/37912371-0f346f44-311b-11e8-8a32-0ac0cd766056.png)

**Comment by ZFi88** [comment]
готово
